---
- name: Fonchastreet web server config
  hosts: fonchastreet_web

  tasks:
   - name: Installing Python
     raw: yum -y install python
     become: true

   - name: Installing Nginx
     yum:
       name: nginx
       state: present

   - name: Start Nginx
     service:
        name: nginx
        state: started
 
